### ISSUE TITLE
Map zoom doesn't work using mouse scroll

### ISSUE THREAD

**Issue by iglesiasroberto14** [redmascotera/redmascotera-front#11]
## Expected Behavior

Use mouse scroll to zoom in and out

## Current Behavior

Nothing happens when mouse scroll is used over map

## Possible Solution

N/A

## Steps to Reproduce

1. Go to https://app.redmascotera.com.ar:9443/pet-lost/maps
2. Try to zoom in/out using scroll

## Context (Environment)

N/A

## Detailed Description

N/A

## Possible Implementation

N/A

**Comment by AgusT613** [comment]
@iglesiasroberto14

I created a pull request to fix this issue: https://github.com/redmascotera/redmascotera-front/pull/12
