### ISSUE TITLE
Error: 'sharp' is required to be installed in standalone mode for the image optimization

### ISSUE THREAD

**Issue by iglesiasroberto14** [redmascotera/redmascotera-front#13]
**Describe the bug**
Found this in container logs every time an image is loaded

```
Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
```

**To Reproduce**
1. `docker run --rm -it -p 3000:3000 redm-front`
2. Go to http://localhost:3000/
3. See container logs  (`docker logs redm-front`)

**Expected behavior**

N/A

**Screenshots**

N/A

**Desktop (please complete the following information):**

 - OS: MacOS
 - Browser Chrome
 - Version 122.0.6261.129

**Smartphone (please complete the following information):**
 
N/A

**Additional context**
N/A

**Comment by AgusT613** [comment]
@iglesiasroberto14

I created a pull request to fix this issue: https://github.com/redmascotera/redmascotera-front/pull/14
